// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.5
// source: dwango/nicolive/chat/data/atoms/akashic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AkashicMessageEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       string           `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	PlayId     string           `protobuf:"bytes,2,opt,name=playId,proto3" json:"playId,omitempty"`
	Ignorable  bool             `protobuf:"varint,3,opt,name=ignorable,proto3" json:"ignorable,omitempty"`
	Transient  bool             `protobuf:"varint,4,opt,name=transient,proto3" json:"transient,omitempty"`
	Parameters *structpb.Struct `protobuf:"bytes,5,opt,name=parameters,proto3" json:"parameters,omitempty"`
}

func (x *AkashicMessageEvent) Reset() {
	*x = AkashicMessageEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dwango_nicolive_chat_data_atoms_akashic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AkashicMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AkashicMessageEvent) ProtoMessage() {}

func (x *AkashicMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_dwango_nicolive_chat_data_atoms_akashic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AkashicMessageEvent.ProtoReflect.Descriptor instead.
func (*AkashicMessageEvent) Descriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDescGZIP(), []int{0}
}

func (x *AkashicMessageEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AkashicMessageEvent) GetPlayId() string {
	if x != nil {
		return x.PlayId
	}
	return ""
}

func (x *AkashicMessageEvent) GetIgnorable() bool {
	if x != nil {
		return x.Ignorable
	}
	return false
}

func (x *AkashicMessageEvent) GetTransient() bool {
	if x != nil {
		return x.Transient
	}
	return false
}

func (x *AkashicMessageEvent) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type AkashicStateRouting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch        int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Join         []*AkashicMessageEvent `protobuf:"bytes,2,rep,name=join,proto3" json:"join,omitempty"`
	Continuation []*AkashicMessageEvent `protobuf:"bytes,3,rep,name=continuation,proto3" json:"continuation,omitempty"`
	Shared       []*AkashicMessageEvent `protobuf:"bytes,4,rep,name=shared,proto3" json:"shared,omitempty"`
}

func (x *AkashicStateRouting) Reset() {
	*x = AkashicStateRouting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dwango_nicolive_chat_data_atoms_akashic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AkashicStateRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AkashicStateRouting) ProtoMessage() {}

func (x *AkashicStateRouting) ProtoReflect() protoreflect.Message {
	mi := &file_dwango_nicolive_chat_data_atoms_akashic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AkashicStateRouting.ProtoReflect.Descriptor instead.
func (*AkashicStateRouting) Descriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDescGZIP(), []int{1}
}

func (x *AkashicStateRouting) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *AkashicStateRouting) GetJoin() []*AkashicMessageEvent {
	if x != nil {
		return x.Join
	}
	return nil
}

func (x *AkashicStateRouting) GetContinuation() []*AkashicMessageEvent {
	if x != nil {
		return x.Continuation
	}
	return nil
}

func (x *AkashicStateRouting) GetShared() []*AkashicMessageEvent {
	if x != nil {
		return x.Shared
	}
	return nil
}

var File_dwango_nicolive_chat_data_atoms_akashic_proto protoreflect.FileDescriptor

var file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76,
	0x65, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x74, 0x6f, 0x6d,
	0x73, 0x2f, 0x61, 0x6b, 0x61, 0x73, 0x68, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1f, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x73,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb6,
	0x01, 0x0a, 0x13, 0x41, 0x6b, 0x61, 0x73, 0x68, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x37,
	0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0a, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x9d, 0x02, 0x0a, 0x13, 0x41, 0x6b, 0x61, 0x73,
	0x68, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x48, 0x0a, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e, 0x69, 0x63,
	0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x61, 0x74, 0x6f, 0x6d, 0x73, 0x2e, 0x41, 0x6b, 0x61, 0x73, 0x68, 0x69, 0x63, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x12,
	0x58, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e,
	0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x73, 0x2e, 0x41, 0x6b, 0x61, 0x73, 0x68, 0x69, 0x63, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0c, 0x63, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4c, 0x0a, 0x06, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x64, 0x77, 0x61, 0x6e,
	0x67, 0x6f, 0x2e, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x73, 0x2e, 0x41, 0x6b, 0x61, 0x73,
	0x68, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDescOnce sync.Once
	file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDescData = file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDesc
)

func file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDescGZIP() []byte {
	file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDescOnce.Do(func() {
		file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDescData = protoimpl.X.CompressGZIP(file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDescData)
	})
	return file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDescData
}

var file_dwango_nicolive_chat_data_atoms_akashic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dwango_nicolive_chat_data_atoms_akashic_proto_goTypes = []any{
	(*AkashicMessageEvent)(nil), // 0: dwango.nicolive.chat.data.atoms.AkashicMessageEvent
	(*AkashicStateRouting)(nil), // 1: dwango.nicolive.chat.data.atoms.AkashicStateRouting
	(*structpb.Struct)(nil),     // 2: google.protobuf.Struct
}
var file_dwango_nicolive_chat_data_atoms_akashic_proto_depIdxs = []int32{
	2, // 0: dwango.nicolive.chat.data.atoms.AkashicMessageEvent.parameters:type_name -> google.protobuf.Struct
	0, // 1: dwango.nicolive.chat.data.atoms.AkashicStateRouting.join:type_name -> dwango.nicolive.chat.data.atoms.AkashicMessageEvent
	0, // 2: dwango.nicolive.chat.data.atoms.AkashicStateRouting.continuation:type_name -> dwango.nicolive.chat.data.atoms.AkashicMessageEvent
	0, // 3: dwango.nicolive.chat.data.atoms.AkashicStateRouting.shared:type_name -> dwango.nicolive.chat.data.atoms.AkashicMessageEvent
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dwango_nicolive_chat_data_atoms_akashic_proto_init() }
func file_dwango_nicolive_chat_data_atoms_akashic_proto_init() {
	if File_dwango_nicolive_chat_data_atoms_akashic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dwango_nicolive_chat_data_atoms_akashic_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AkashicMessageEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dwango_nicolive_chat_data_atoms_akashic_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AkashicStateRouting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dwango_nicolive_chat_data_atoms_akashic_proto_goTypes,
		DependencyIndexes: file_dwango_nicolive_chat_data_atoms_akashic_proto_depIdxs,
		MessageInfos:      file_dwango_nicolive_chat_data_atoms_akashic_proto_msgTypes,
	}.Build()
	File_dwango_nicolive_chat_data_atoms_akashic_proto = out.File
	file_dwango_nicolive_chat_data_atoms_akashic_proto_rawDesc = nil
	file_dwango_nicolive_chat_data_atoms_akashic_proto_goTypes = nil
	file_dwango_nicolive_chat_data_atoms_akashic_proto_depIdxs = nil
}
