// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.5
// source: dwango/nicolive/chat/data/atoms/forwarded.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardedChat_ForwardingMode int32

const (
	ForwardedChat_UNKNOWN        ForwardedChat_ForwardingMode = 0
	ForwardedChat_FROM_CRUISE    ForwardedChat_ForwardingMode = 1
	ForwardedChat_COLLAB_SHARING ForwardedChat_ForwardingMode = 2
)

// Enum value maps for ForwardedChat_ForwardingMode.
var (
	ForwardedChat_ForwardingMode_name = map[int32]string{
		0: "UNKNOWN",
		1: "FROM_CRUISE",
		2: "COLLAB_SHARING",
	}
	ForwardedChat_ForwardingMode_value = map[string]int32{
		"UNKNOWN":        0,
		"FROM_CRUISE":    1,
		"COLLAB_SHARING": 2,
	}
)

func (x ForwardedChat_ForwardingMode) Enum() *ForwardedChat_ForwardingMode {
	p := new(ForwardedChat_ForwardingMode)
	*p = x
	return p
}

func (x ForwardedChat_ForwardingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForwardedChat_ForwardingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_dwango_nicolive_chat_data_atoms_forwarded_proto_enumTypes[0].Descriptor()
}

func (ForwardedChat_ForwardingMode) Type() protoreflect.EnumType {
	return &file_dwango_nicolive_chat_data_atoms_forwarded_proto_enumTypes[0]
}

func (x ForwardedChat_ForwardingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForwardedChat_ForwardingMode.Descriptor instead.
func (ForwardedChat_ForwardingMode) EnumDescriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDescGZIP(), []int{0, 0}
}

type ForwardedChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chat         *Chat                        `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	MessageId    string                       `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SourceLiveId int64                        `protobuf:"varint,3,opt,name=source_live_id,json=sourceLiveId,proto3" json:"source_live_id,omitempty"`
	Mode         ForwardedChat_ForwardingMode `protobuf:"varint,4,opt,name=mode,proto3,enum=dwango.nicolive.chat.data.atoms.ForwardedChat_ForwardingMode" json:"mode,omitempty"`
}

func (x *ForwardedChat) Reset() {
	*x = ForwardedChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dwango_nicolive_chat_data_atoms_forwarded_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardedChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardedChat) ProtoMessage() {}

func (x *ForwardedChat) ProtoReflect() protoreflect.Message {
	mi := &file_dwango_nicolive_chat_data_atoms_forwarded_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardedChat.ProtoReflect.Descriptor instead.
func (*ForwardedChat) Descriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardedChat) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *ForwardedChat) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ForwardedChat) GetSourceLiveId() int64 {
	if x != nil {
		return x.SourceLiveId
	}
	return 0
}

func (x *ForwardedChat) GetMode() ForwardedChat_ForwardingMode {
	if x != nil {
		return x.Mode
	}
	return ForwardedChat_UNKNOWN
}

var File_dwango_nicolive_chat_data_atoms_forwarded_proto protoreflect.FileDescriptor

var file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76,
	0x65, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x74, 0x6f, 0x6d,
	0x73, 0x2f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1f, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69,
	0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x61, 0x74, 0x6f,
	0x6d, 0x73, 0x1a, 0x25, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x6e, 0x69, 0x63, 0x6f, 0x6c,
	0x69, 0x76, 0x65, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x74,
	0x6f, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x02, 0x0a, 0x0d, 0x46, 0x6f,
	0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x43, 0x68, 0x61, 0x74, 0x12, 0x33, 0x0a, 0x04, 0x63,
	0x68, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x77, 0x61, 0x6e,
	0x67, 0x6f, 0x2e, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c,
	0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x51, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x3d, 0x2e, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e, 0x69, 0x63,
	0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x61, 0x74, 0x6f, 0x6d, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x43,
	0x68, 0x61, 0x74, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x42, 0x0a, 0x0e, 0x46, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x52, 0x4f, 0x4d, 0x5f,
	0x43, 0x52, 0x55, 0x49, 0x53, 0x45, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x4c, 0x4c,
	0x41, 0x42, 0x5f, 0x53, 0x48, 0x41, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDescOnce sync.Once
	file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDescData = file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDesc
)

func file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDescGZIP() []byte {
	file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDescOnce.Do(func() {
		file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDescData = protoimpl.X.CompressGZIP(file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDescData)
	})
	return file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDescData
}

var file_dwango_nicolive_chat_data_atoms_forwarded_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dwango_nicolive_chat_data_atoms_forwarded_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dwango_nicolive_chat_data_atoms_forwarded_proto_goTypes = []any{
	(ForwardedChat_ForwardingMode)(0), // 0: dwango.nicolive.chat.data.atoms.ForwardedChat.ForwardingMode
	(*ForwardedChat)(nil),             // 1: dwango.nicolive.chat.data.atoms.ForwardedChat
	(*Chat)(nil),                      // 2: dwango.nicolive.chat.data.Chat
}
var file_dwango_nicolive_chat_data_atoms_forwarded_proto_depIdxs = []int32{
	2, // 0: dwango.nicolive.chat.data.atoms.ForwardedChat.chat:type_name -> dwango.nicolive.chat.data.Chat
	0, // 1: dwango.nicolive.chat.data.atoms.ForwardedChat.mode:type_name -> dwango.nicolive.chat.data.atoms.ForwardedChat.ForwardingMode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dwango_nicolive_chat_data_atoms_forwarded_proto_init() }
func file_dwango_nicolive_chat_data_atoms_forwarded_proto_init() {
	if File_dwango_nicolive_chat_data_atoms_forwarded_proto != nil {
		return
	}
	file_dwango_nicolive_chat_data_atoms_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dwango_nicolive_chat_data_atoms_forwarded_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ForwardedChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dwango_nicolive_chat_data_atoms_forwarded_proto_goTypes,
		DependencyIndexes: file_dwango_nicolive_chat_data_atoms_forwarded_proto_depIdxs,
		EnumInfos:         file_dwango_nicolive_chat_data_atoms_forwarded_proto_enumTypes,
		MessageInfos:      file_dwango_nicolive_chat_data_atoms_forwarded_proto_msgTypes,
	}.Build()
	File_dwango_nicolive_chat_data_atoms_forwarded_proto = out.File
	file_dwango_nicolive_chat_data_atoms_forwarded_proto_rawDesc = nil
	file_dwango_nicolive_chat_data_atoms_forwarded_proto_goTypes = nil
	file_dwango_nicolive_chat_data_atoms_forwarded_proto_depIdxs = nil
}
