// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.5
// source: dwango/nicolive/chat/data/atoms/ichibalauncher.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IchibaLauncherItemSet_Item_LaunchDialogType int32

const (
	IchibaLauncherItemSet_Item_SMALL     IchibaLauncherItemSet_Item_LaunchDialogType = 0
	IchibaLauncherItemSet_Item_RICHIVIEW IchibaLauncherItemSet_Item_LaunchDialogType = 1
)

// Enum value maps for IchibaLauncherItemSet_Item_LaunchDialogType.
var (
	IchibaLauncherItemSet_Item_LaunchDialogType_name = map[int32]string{
		0: "SMALL",
		1: "RICHIVIEW",
	}
	IchibaLauncherItemSet_Item_LaunchDialogType_value = map[string]int32{
		"SMALL":     0,
		"RICHIVIEW": 1,
	}
)

func (x IchibaLauncherItemSet_Item_LaunchDialogType) Enum() *IchibaLauncherItemSet_Item_LaunchDialogType {
	p := new(IchibaLauncherItemSet_Item_LaunchDialogType)
	*p = x
	return p
}

func (x IchibaLauncherItemSet_Item_LaunchDialogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IchibaLauncherItemSet_Item_LaunchDialogType) Descriptor() protoreflect.EnumDescriptor {
	return file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_enumTypes[0].Descriptor()
}

func (IchibaLauncherItemSet_Item_LaunchDialogType) Type() protoreflect.EnumType {
	return &file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_enumTypes[0]
}

func (x IchibaLauncherItemSet_Item_LaunchDialogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IchibaLauncherItemSet_Item_LaunchDialogType.Descriptor instead.
func (IchibaLauncherItemSet_Item_LaunchDialogType) EnumDescriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDescGZIP(), []int{0, 0, 0}
}

type IchibaLauncherItemSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch int64                         `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Items []*IchibaLauncherItemSet_Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *IchibaLauncherItemSet) Reset() {
	*x = IchibaLauncherItemSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IchibaLauncherItemSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IchibaLauncherItemSet) ProtoMessage() {}

func (x *IchibaLauncherItemSet) ProtoReflect() protoreflect.Message {
	mi := &file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IchibaLauncherItemSet.ProtoReflect.Descriptor instead.
func (*IchibaLauncherItemSet) Descriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDescGZIP(), []int{0}
}

func (x *IchibaLauncherItemSet) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *IchibaLauncherItemSet) GetItems() []*IchibaLauncherItemSet_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type IchibaLauncherItemSet_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string                                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityId         string                                      `protobuf:"bytes,2,opt,name=entityId,proto3" json:"entityId,omitempty"`
	ServiceName      string                                      `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Title            string                                      `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	LaunchDialogType IchibaLauncherItemSet_Item_LaunchDialogType `protobuf:"varint,5,opt,name=launchDialogType,proto3,enum=dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet_Item_LaunchDialogType" json:"launchDialogType,omitempty"`
	ThumbnailUrl     string                                      `protobuf:"bytes,6,opt,name=thumbnailUrl,proto3" json:"thumbnailUrl,omitempty"`
	ThumbnailWidth   int32                                       `protobuf:"varint,7,opt,name=thumbnailWidth,proto3" json:"thumbnailWidth,omitempty"`
	ThumbnailHeight  int32                                       `protobuf:"varint,8,opt,name=thumbnailHeight,proto3" json:"thumbnailHeight,omitempty"`
	LaunchUrl        string                                      `protobuf:"bytes,9,opt,name=launchUrl,proto3" json:"launchUrl,omitempty"`
	AddedUserId      *string                                     `protobuf:"bytes,10,opt,name=addedUserId,proto3,oneof" json:"addedUserId,omitempty"`
	ReportUrl        *string                                     `protobuf:"bytes,11,opt,name=reportUrl,proto3,oneof" json:"reportUrl,omitempty"`
	Running          bool                                        `protobuf:"varint,12,opt,name=running,proto3" json:"running,omitempty"`
}

func (x *IchibaLauncherItemSet_Item) Reset() {
	*x = IchibaLauncherItemSet_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IchibaLauncherItemSet_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IchibaLauncherItemSet_Item) ProtoMessage() {}

func (x *IchibaLauncherItemSet_Item) ProtoReflect() protoreflect.Message {
	mi := &file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IchibaLauncherItemSet_Item.ProtoReflect.Descriptor instead.
func (*IchibaLauncherItemSet_Item) Descriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDescGZIP(), []int{0, 0}
}

func (x *IchibaLauncherItemSet_Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IchibaLauncherItemSet_Item) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *IchibaLauncherItemSet_Item) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *IchibaLauncherItemSet_Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IchibaLauncherItemSet_Item) GetLaunchDialogType() IchibaLauncherItemSet_Item_LaunchDialogType {
	if x != nil {
		return x.LaunchDialogType
	}
	return IchibaLauncherItemSet_Item_SMALL
}

func (x *IchibaLauncherItemSet_Item) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *IchibaLauncherItemSet_Item) GetThumbnailWidth() int32 {
	if x != nil {
		return x.ThumbnailWidth
	}
	return 0
}

func (x *IchibaLauncherItemSet_Item) GetThumbnailHeight() int32 {
	if x != nil {
		return x.ThumbnailHeight
	}
	return 0
}

func (x *IchibaLauncherItemSet_Item) GetLaunchUrl() string {
	if x != nil {
		return x.LaunchUrl
	}
	return ""
}

func (x *IchibaLauncherItemSet_Item) GetAddedUserId() string {
	if x != nil && x.AddedUserId != nil {
		return *x.AddedUserId
	}
	return ""
}

func (x *IchibaLauncherItemSet_Item) GetReportUrl() string {
	if x != nil && x.ReportUrl != nil {
		return *x.ReportUrl
	}
	return ""
}

func (x *IchibaLauncherItemSet_Item) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

var File_dwango_nicolive_chat_data_atoms_ichibalauncher_proto protoreflect.FileDescriptor

var file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDesc = []byte{
	0x0a, 0x34, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76,
	0x65, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x74, 0x6f, 0x6d,
	0x73, 0x2f, 0x69, 0x63, 0x68, 0x69, 0x62, 0x61, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e,
	0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x73, 0x22, 0xab, 0x05, 0x0a, 0x15, 0x49, 0x63, 0x68, 0x69,
	0x62, 0x61, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x65,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x51, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e,
	0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x73, 0x2e, 0x49, 0x63, 0x68, 0x69, 0x62, 0x61, 0x4c,
	0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x74, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0xa8, 0x04, 0x0a, 0x04, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x78, 0x0a, 0x10, 0x6c, 0x61, 0x75, 0x6e, 0x63,
	0x68, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x4c, 0x2e, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e, 0x69, 0x63, 0x6f, 0x6c,
	0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x61, 0x74,
	0x6f, 0x6d, 0x73, 0x2e, 0x49, 0x63, 0x68, 0x69, 0x62, 0x61, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x4c,
	0x61, 0x75, 0x6e, 0x63, 0x68, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x10, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x55, 0x72,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74,
	0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x28, 0x0a,
	0x0f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69,
	0x6c, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x61, 0x75, 0x6e, 0x63,
	0x68, 0x55, 0x72, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x61, 0x75, 0x6e,
	0x63, 0x68, 0x55, 0x72, 0x6c, 0x12, 0x25, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x65, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x64,
	0x64, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x2c, 0x0a, 0x10, 0x4c, 0x61, 0x75,
	0x6e, 0x63, 0x68, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x53, 0x4d, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x49, 0x43, 0x48,
	0x49, 0x56, 0x49, 0x45, 0x57, 0x10, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x61, 0x64, 0x64, 0x65,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDescOnce sync.Once
	file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDescData = file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDesc
)

func file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDescGZIP() []byte {
	file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDescOnce.Do(func() {
		file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDescData = protoimpl.X.CompressGZIP(file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDescData)
	})
	return file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDescData
}

var file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_goTypes = []any{
	(IchibaLauncherItemSet_Item_LaunchDialogType)(0), // 0: dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item.LaunchDialogType
	(*IchibaLauncherItemSet)(nil),                    // 1: dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet
	(*IchibaLauncherItemSet_Item)(nil),               // 2: dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item
}
var file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_depIdxs = []int32{
	2, // 0: dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.items:type_name -> dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item
	0, // 1: dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item.launchDialogType:type_name -> dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item.LaunchDialogType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_init() }
func file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_init() {
	if File_dwango_nicolive_chat_data_atoms_ichibalauncher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IchibaLauncherItemSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IchibaLauncherItemSet_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_goTypes,
		DependencyIndexes: file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_depIdxs,
		EnumInfos:         file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_enumTypes,
		MessageInfos:      file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_msgTypes,
	}.Build()
	File_dwango_nicolive_chat_data_atoms_ichibalauncher_proto = out.File
	file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_rawDesc = nil
	file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_goTypes = nil
	file_dwango_nicolive_chat_data_atoms_ichibalauncher_proto_depIdxs = nil
}
