// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.5
// source: dwango/nicolive/chat/data/atoms/notifications.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleNotificationV2_NotificationType int32

const (
	SimpleNotificationV2_UNKNOWN              SimpleNotificationV2_NotificationType = 0
	SimpleNotificationV2_ICHIBA               SimpleNotificationV2_NotificationType = 1
	SimpleNotificationV2_EMOTION              SimpleNotificationV2_NotificationType = 2
	SimpleNotificationV2_CRUISE               SimpleNotificationV2_NotificationType = 3
	SimpleNotificationV2_PROGRAM_EXTENDED     SimpleNotificationV2_NotificationType = 4
	SimpleNotificationV2_RANKING_IN           SimpleNotificationV2_NotificationType = 5
	SimpleNotificationV2_VISITED              SimpleNotificationV2_NotificationType = 6
	SimpleNotificationV2_SUPPORTER_REGISTERED SimpleNotificationV2_NotificationType = 7
	SimpleNotificationV2_USER_LEVEL_UP        SimpleNotificationV2_NotificationType = 8
	SimpleNotificationV2_USER_FOLLOW          SimpleNotificationV2_NotificationType = 9
)

// Enum value maps for SimpleNotificationV2_NotificationType.
var (
	SimpleNotificationV2_NotificationType_name = map[int32]string{
		0: "UNKNOWN",
		1: "ICHIBA",
		2: "EMOTION",
		3: "CRUISE",
		4: "PROGRAM_EXTENDED",
		5: "RANKING_IN",
		6: "VISITED",
		7: "SUPPORTER_REGISTERED",
		8: "USER_LEVEL_UP",
		9: "USER_FOLLOW",
	}
	SimpleNotificationV2_NotificationType_value = map[string]int32{
		"UNKNOWN":              0,
		"ICHIBA":               1,
		"EMOTION":              2,
		"CRUISE":               3,
		"PROGRAM_EXTENDED":     4,
		"RANKING_IN":           5,
		"VISITED":              6,
		"SUPPORTER_REGISTERED": 7,
		"USER_LEVEL_UP":        8,
		"USER_FOLLOW":          9,
	}
)

func (x SimpleNotificationV2_NotificationType) Enum() *SimpleNotificationV2_NotificationType {
	p := new(SimpleNotificationV2_NotificationType)
	*p = x
	return p
}

func (x SimpleNotificationV2_NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimpleNotificationV2_NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_dwango_nicolive_chat_data_atoms_notifications_proto_enumTypes[0].Descriptor()
}

func (SimpleNotificationV2_NotificationType) Type() protoreflect.EnumType {
	return &file_dwango_nicolive_chat_data_atoms_notifications_proto_enumTypes[0]
}

func (x SimpleNotificationV2_NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimpleNotificationV2_NotificationType.Descriptor instead.
func (SimpleNotificationV2_NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDescGZIP(), []int{0, 0}
}

type SimpleNotificationV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        SimpleNotificationV2_NotificationType `protobuf:"varint,1,opt,name=type,proto3,enum=dwango.nicolive.chat.data.atoms.SimpleNotificationV2_NotificationType" json:"type,omitempty"`
	Message     string                                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ShowInTelop bool                                  `protobuf:"varint,3,opt,name=show_in_telop,json=showInTelop,proto3" json:"show_in_telop,omitempty"`
	ShowInList  bool                                  `protobuf:"varint,4,opt,name=show_in_list,json=showInList,proto3" json:"show_in_list,omitempty"`
}

func (x *SimpleNotificationV2) Reset() {
	*x = SimpleNotificationV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dwango_nicolive_chat_data_atoms_notifications_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleNotificationV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleNotificationV2) ProtoMessage() {}

func (x *SimpleNotificationV2) ProtoReflect() protoreflect.Message {
	mi := &file_dwango_nicolive_chat_data_atoms_notifications_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleNotificationV2.ProtoReflect.Descriptor instead.
func (*SimpleNotificationV2) Descriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleNotificationV2) GetType() SimpleNotificationV2_NotificationType {
	if x != nil {
		return x.Type
	}
	return SimpleNotificationV2_UNKNOWN
}

func (x *SimpleNotificationV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SimpleNotificationV2) GetShowInTelop() bool {
	if x != nil {
		return x.ShowInTelop
	}
	return false
}

func (x *SimpleNotificationV2) GetShowInList() bool {
	if x != nil {
		return x.ShowInList
	}
	return false
}

var File_dwango_nicolive_chat_data_atoms_notifications_proto protoreflect.FileDescriptor

var file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDesc = []byte{
	0x0a, 0x33, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76,
	0x65, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x74, 0x6f, 0x6d,
	0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e, 0x69,
	0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x73, 0x22, 0x8a, 0x03, 0x0a, 0x14, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x32, 0x12,
	0x5a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x46, 0x2e,
	0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x73, 0x2e,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x56, 0x32, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x69, 0x6e,
	0x5f, 0x74, 0x65, 0x6c, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73, 0x68,
	0x6f, 0x77, 0x49, 0x6e, 0x54, 0x65, 0x6c, 0x6f, 0x70, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x68, 0x6f,
	0x77, 0x5f, 0x69, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x73, 0x68, 0x6f, 0x77, 0x49, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xb5, 0x01, 0x0a, 0x10,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x49, 0x43, 0x48, 0x49, 0x42, 0x41, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x4d, 0x4f,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x55, 0x49, 0x53, 0x45,
	0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x41, 0x4d, 0x5f, 0x45, 0x58,
	0x54, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x41, 0x4e, 0x4b,
	0x49, 0x4e, 0x47, 0x5f, 0x49, 0x4e, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x49, 0x53, 0x49,
	0x54, 0x45, 0x44, 0x10, 0x06, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54,
	0x45, 0x52, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x10, 0x07, 0x12,
	0x11, 0x0a, 0x0d, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x55, 0x50,
	0x10, 0x08, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x46, 0x4f, 0x4c, 0x4c, 0x4f,
	0x57, 0x10, 0x09, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDescOnce sync.Once
	file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDescData = file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDesc
)

func file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDescGZIP() []byte {
	file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDescOnce.Do(func() {
		file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDescData)
	})
	return file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDescData
}

var file_dwango_nicolive_chat_data_atoms_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dwango_nicolive_chat_data_atoms_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dwango_nicolive_chat_data_atoms_notifications_proto_goTypes = []any{
	(SimpleNotificationV2_NotificationType)(0), // 0: dwango.nicolive.chat.data.atoms.SimpleNotificationV2.NotificationType
	(*SimpleNotificationV2)(nil),               // 1: dwango.nicolive.chat.data.atoms.SimpleNotificationV2
}
var file_dwango_nicolive_chat_data_atoms_notifications_proto_depIdxs = []int32{
	0, // 0: dwango.nicolive.chat.data.atoms.SimpleNotificationV2.type:type_name -> dwango.nicolive.chat.data.atoms.SimpleNotificationV2.NotificationType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dwango_nicolive_chat_data_atoms_notifications_proto_init() }
func file_dwango_nicolive_chat_data_atoms_notifications_proto_init() {
	if File_dwango_nicolive_chat_data_atoms_notifications_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dwango_nicolive_chat_data_atoms_notifications_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SimpleNotificationV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dwango_nicolive_chat_data_atoms_notifications_proto_goTypes,
		DependencyIndexes: file_dwango_nicolive_chat_data_atoms_notifications_proto_depIdxs,
		EnumInfos:         file_dwango_nicolive_chat_data_atoms_notifications_proto_enumTypes,
		MessageInfos:      file_dwango_nicolive_chat_data_atoms_notifications_proto_msgTypes,
	}.Build()
	File_dwango_nicolive_chat_data_atoms_notifications_proto = out.File
	file_dwango_nicolive_chat_data_atoms_notifications_proto_rawDesc = nil
	file_dwango_nicolive_chat_data_atoms_notifications_proto_goTypes = nil
	file_dwango_nicolive_chat_data_atoms_notifications_proto_depIdxs = nil
}
