// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: origin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NicoliveOrigin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Origin:
	//
	//	*NicoliveOrigin_Chat_
	Origin isNicoliveOrigin_Origin `protobuf_oneof:"origin"`
}

func (x *NicoliveOrigin) Reset() {
	*x = NicoliveOrigin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NicoliveOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicoliveOrigin) ProtoMessage() {}

func (x *NicoliveOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicoliveOrigin.ProtoReflect.Descriptor instead.
func (*NicoliveOrigin) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0}
}

func (m *NicoliveOrigin) GetOrigin() isNicoliveOrigin_Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (x *NicoliveOrigin) GetChat() *NicoliveOrigin_Chat {
	if x, ok := x.GetOrigin().(*NicoliveOrigin_Chat_); ok {
		return x.Chat
	}
	return nil
}

type isNicoliveOrigin_Origin interface {
	isNicoliveOrigin_Origin()
}

type NicoliveOrigin_Chat_ struct {
	Chat *NicoliveOrigin_Chat `protobuf:"bytes,1,opt,name=chat,proto3,oneof"`
}

func (*NicoliveOrigin_Chat_) isNicoliveOrigin_Origin() {}

type NicoliveOrigin_Chat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LiveId int64 `protobuf:"varint,1,opt,name=live_id,json=liveId,proto3" json:"live_id,omitempty"`
}

func (x *NicoliveOrigin_Chat) Reset() {
	*x = NicoliveOrigin_Chat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NicoliveOrigin_Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicoliveOrigin_Chat) ProtoMessage() {}

func (x *NicoliveOrigin_Chat) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicoliveOrigin_Chat.ProtoReflect.Descriptor instead.
func (*NicoliveOrigin_Chat) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NicoliveOrigin_Chat) GetLiveId() int64 {
	if x != nil {
		return x.LiveId
	}
	return 0
}

var File_origin_proto protoreflect.FileDescriptor

var file_origin_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19,
	0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x22, 0x81, 0x01, 0x0a, 0x0e, 0x4e, 0x69,
	0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x44, 0x0a, 0x04,
	0x63, 0x68, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x64, 0x77, 0x61,
	0x6e, 0x67, 0x6f, 0x2e, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x4f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x48, 0x00, 0x52, 0x04, 0x63, 0x68,
	0x61, 0x74, 0x1a, 0x1f, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69,
	0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x69, 0x76,
	0x65, 0x49, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_origin_proto_rawDescOnce sync.Once
	file_origin_proto_rawDescData = file_origin_proto_rawDesc
)

func file_origin_proto_rawDescGZIP() []byte {
	file_origin_proto_rawDescOnce.Do(func() {
		file_origin_proto_rawDescData = protoimpl.X.CompressGZIP(file_origin_proto_rawDescData)
	})
	return file_origin_proto_rawDescData
}

var file_origin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_origin_proto_goTypes = []any{
	(*NicoliveOrigin)(nil),      // 0: dwango.nicolive.chat.data.NicoliveOrigin
	(*NicoliveOrigin_Chat)(nil), // 1: dwango.nicolive.chat.data.NicoliveOrigin.Chat
}
var file_origin_proto_depIdxs = []int32{
	1, // 0: dwango.nicolive.chat.data.NicoliveOrigin.chat:type_name -> dwango.nicolive.chat.data.NicoliveOrigin.Chat
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_origin_proto_init() }
func file_origin_proto_init() {
	if File_origin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_origin_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NicoliveOrigin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NicoliveOrigin_Chat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_origin_proto_msgTypes[0].OneofWrappers = []any{
		(*NicoliveOrigin_Chat_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_origin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_origin_proto_goTypes,
		DependencyIndexes: file_origin_proto_depIdxs,
		MessageInfos:      file_origin_proto_msgTypes,
	}.Build()
	File_origin_proto = out.File
	file_origin_proto_rawDesc = nil
	file_origin_proto_goTypes = nil
	file_origin_proto_depIdxs = nil
}
