// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.5
// source: dwango/nicolive/chat/data/atoms/streamstate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamStateChange_State int32

const (
	StreamStateChange_PASSTHROUGH StreamStateChange_State = 0
	StreamStateChange_PROCESSED   StreamStateChange_State = 1
)

// Enum value maps for StreamStateChange_State.
var (
	StreamStateChange_State_name = map[int32]string{
		0: "PASSTHROUGH",
		1: "PROCESSED",
	}
	StreamStateChange_State_value = map[string]int32{
		"PASSTHROUGH": 0,
		"PROCESSED":   1,
	}
)

func (x StreamStateChange_State) Enum() *StreamStateChange_State {
	p := new(StreamStateChange_State)
	*p = x
	return p
}

func (x StreamStateChange_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamStateChange_State) Descriptor() protoreflect.EnumDescriptor {
	return file_dwango_nicolive_chat_data_atoms_streamstate_proto_enumTypes[0].Descriptor()
}

func (StreamStateChange_State) Type() protoreflect.EnumType {
	return &file_dwango_nicolive_chat_data_atoms_streamstate_proto_enumTypes[0]
}

func (x StreamStateChange_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamStateChange_State.Descriptor instead.
func (StreamStateChange_State) EnumDescriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDescGZIP(), []int{0, 0}
}

type StreamStateChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch int64                   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	State StreamStateChange_State `protobuf:"varint,2,opt,name=state,proto3,enum=dwango.nicolive.chat.data.atoms.StreamStateChange_State" json:"state,omitempty"`
}

func (x *StreamStateChange) Reset() {
	*x = StreamStateChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dwango_nicolive_chat_data_atoms_streamstate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStateChange) ProtoMessage() {}

func (x *StreamStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_dwango_nicolive_chat_data_atoms_streamstate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStateChange.ProtoReflect.Descriptor instead.
func (*StreamStateChange) Descriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDescGZIP(), []int{0}
}

func (x *StreamStateChange) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *StreamStateChange) GetState() StreamStateChange_State {
	if x != nil {
		return x.State
	}
	return StreamStateChange_PASSTHROUGH
}

var File_dwango_nicolive_chat_data_atoms_streamstate_proto protoreflect.FileDescriptor

var file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDesc = []byte{
	0x0a, 0x31, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76,
	0x65, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x74, 0x6f, 0x6d,
	0x73, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e, 0x69, 0x63, 0x6f,
	0x6c, 0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x61,
	0x74, 0x6f, 0x6d, 0x73, 0x22, 0xa2, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70,
	0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x12, 0x4e, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x38, 0x2e, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76,
	0x65, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x61, 0x74, 0x6f, 0x6d,
	0x73, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x22, 0x27, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x41, 0x53,
	0x53, 0x54, 0x48, 0x52, 0x4f, 0x55, 0x47, 0x48, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x52,
	0x4f, 0x43, 0x45, 0x53, 0x53, 0x45, 0x44, 0x10, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDescOnce sync.Once
	file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDescData = file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDesc
)

func file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDescGZIP() []byte {
	file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDescOnce.Do(func() {
		file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDescData = protoimpl.X.CompressGZIP(file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDescData)
	})
	return file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDescData
}

var file_dwango_nicolive_chat_data_atoms_streamstate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dwango_nicolive_chat_data_atoms_streamstate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dwango_nicolive_chat_data_atoms_streamstate_proto_goTypes = []any{
	(StreamStateChange_State)(0), // 0: dwango.nicolive.chat.data.atoms.StreamStateChange.State
	(*StreamStateChange)(nil),    // 1: dwango.nicolive.chat.data.atoms.StreamStateChange
}
var file_dwango_nicolive_chat_data_atoms_streamstate_proto_depIdxs = []int32{
	0, // 0: dwango.nicolive.chat.data.atoms.StreamStateChange.state:type_name -> dwango.nicolive.chat.data.atoms.StreamStateChange.State
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dwango_nicolive_chat_data_atoms_streamstate_proto_init() }
func file_dwango_nicolive_chat_data_atoms_streamstate_proto_init() {
	if File_dwango_nicolive_chat_data_atoms_streamstate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dwango_nicolive_chat_data_atoms_streamstate_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StreamStateChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dwango_nicolive_chat_data_atoms_streamstate_proto_goTypes,
		DependencyIndexes: file_dwango_nicolive_chat_data_atoms_streamstate_proto_depIdxs,
		EnumInfos:         file_dwango_nicolive_chat_data_atoms_streamstate_proto_enumTypes,
		MessageInfos:      file_dwango_nicolive_chat_data_atoms_streamstate_proto_msgTypes,
	}.Build()
	File_dwango_nicolive_chat_data_atoms_streamstate_proto = out.File
	file_dwango_nicolive_chat_data_atoms_streamstate_proto_rawDesc = nil
	file_dwango_nicolive_chat_data_atoms_streamstate_proto_goTypes = nil
	file_dwango_nicolive_chat_data_atoms_streamstate_proto_depIdxs = nil
}
